# Generated by Django 4.1.6 on 2023-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.CharField(blank=True, choices=[('Yes', 'Published'), ('No', 'Draft')], max_length=100, null=True),
        ),
    ]
